tasks:
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - esbenp.prettier-vscode
    - garaioag.garaio-vscode-unwanted-recommendations
    - github.vscode-github-actions
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
