ci:
  autoupdate_commit_msg: "MAINT: update lock files"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ComPWA/policy
    rev: 0.5.0rc8
    hooks:
      - id: check-dev-files
        args:
          - --no-cd
          - --keep-issue-templates
          - --no-python
          - --no-pypi
          - --repo-name=.github
          - --repo-title=Public ComPWA GitHub profile

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.3.3
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args: [--in-place]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.15.1
    hooks:
      - id: cspell
