ci:
  autoupdate_commit_msg: "ci: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/repo-maintenance
    rev: 0.0.34
    hooks:
      - id: check-dev-files
        args:
          - --no-prettierrc

  - repo: https://github.com/ComPWA/mirrors-cspell
    rev: v5.10.1
    hooks:
      - id: cspell

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
