name: Feature request
description: Suggest an idea for this project
labels:
  - ✨ Feature
assignees:
  # cspell: ignore redeboer shenvitor
  - redeboer
  - shenvitor
projects:
  - ComPWA/5

body:
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: >-
        Is your feature request related to a problem?
        Please provide a clear and  concise description of what the problem is.
      placeholder: |
        Example: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd want to happen. Are there alternatives you have considered?
      placeholder: |
        I would like to see ...
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: What should the interface look like?
      description: If you already have some ideas, write some code snippets that describe the interface behavior you would like to see!
      placeholder: Write your Python code here
      render: python3

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature here.
